### ISSUE TITLE
Cleanup Todo's

### ISSUE THREAD

**Issue by Rperry2174** [faiz121/react-redux-express-pg#2]
### Cleanup Todos
- [ ] Virtual Box setup
- [ ] Requirements.txt for required python packages
- [ ] Global config for db information
